title: "UIL Documentation"
description: UIL Website Documentation
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true
exclude: []

# Aux links for the upper right navigation
aux_links:
  "UIL Docs on GitHub":
    - "//github.com/grcrane/jtd-remote"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false